In [1]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
data = pd.read_csv(r"examples/ex5.csv")

In [6]:
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [7]:
data.to_csv("examples/out.csv")

In [8]:
%pycat examples/out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [9]:
import sys

In [10]:
data.to_csv(sys.stdout, sep = "|")

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [11]:
data.to_csv(sys.stdout, na_rep = "NULL")

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [12]:
data.to_csv(sys.stdout, index = False, header = False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [13]:
data.to_csv(sys.stdout, index = False, columns = ["a", "b", "c"])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [14]:
%pycat examples/ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

In [15]:
import csv

In [16]:
f = open("examples/ex7.csv")

In [17]:
reader = csv.reader(f)

In [18]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [19]:
 f.close()

In [20]:
with open("examples/ex7.csv") as f:
    lines = list(csv.reader(f))

In [22]:
header, values = lines[0], lines[1:]

In [23]:
data_dict = {h: v for h, v in zip(header, zip(*values))}

In [24]:
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [26]:
import json

In [33]:
obj = """
{"name":"wes",
"cities_lived": ["akron", "nashville", "new york", "san francisco"],
"pet": null,
"siblings":[{"name":"scott", "age": 34, "hobbies": ["guitars", "soccer"]},
            {"name" :"kattie", "age": 42, "hobbies": ["driving", "art"]}]
}
"""

In [34]:
result = json.loads(obj)

In [35]:
result

{'name': 'wes',
 'cities_lived': ['akron', 'nashville', 'new york', 'san francisco'],
 'pet': None,
 'siblings': [{'name': 'scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'kattie', 'age': 42, 'hobbies': ['driving', 'art']}]}

In [36]:
asjson = json.dumps(result)

In [38]:
asjson

'{"name": "wes", "cities_lived": ["akron", "nashville", "new york", "san francisco"], "pet": null, "siblings": [{"name": "scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "kattie", "age": 42, "hobbies": ["driving", "art"]}]}'

In [39]:
siblings = pd.DataFrame(result["siblings"], columns = ["name", "age"])

In [40]:
siblings

     name  age
0   scott   34
1  kattie   42

In [41]:
%pycat examples/example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [42]:
data = pd.read_json("examples/example.json")

In [43]:
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [44]:
data.to_json(sys.stdout)

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}