In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
df = pd.DataFrame(np.random.standard_normal((7,3)))

In [5]:
df.iloc[:4,1] = np.nan

In [6]:
df.iloc[:2,2] = np.nan

In [7]:
df.fillna(0)

          0         1         2
0 -0.076295  0.000000  0.000000
1 -0.969352  0.000000  0.000000
2  0.952694  0.000000 -0.548052
3 -0.733219  0.000000 -1.316506
4  1.693442 -0.027308  0.888691
5  0.518975 -1.444595  0.525366
6 -1.130806  0.361175 -0.077263

In [8]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0 -0.076295  0.500000  0.000000
1 -0.969352  0.500000  0.000000
2  0.952694  0.500000 -0.548052
3 -0.733219  0.500000 -1.316506
4  1.693442 -0.027308  0.888691
5  0.518975 -1.444595  0.525366
6 -1.130806  0.361175 -0.077263

In [9]:
df = pd.DataFrame(np.random.standard_normal((6,3)))

In [10]:
df.iloc[2:, 1] = np.nan

In [11]:
df.iloc[4:, 2] = np.nan

In [12]:
df

          0         1         2
0  0.983924  0.178441  0.573742
1 -2.001475 -0.987922 -0.378934
2 -1.198428       NaN -0.804601
3  0.380425       NaN -1.402965
4  0.976994       NaN       NaN
5  2.663640       NaN       NaN

In [14]:
df.ffill

<bound method NDFrame.ffill of           0         1         2
0  0.983924  0.178441  0.573742
1 -2.001475 -0.987922 -0.378934
2 -1.198428       NaN -0.804601
3  0.380425       NaN -1.402965
4  0.976994       NaN       NaN
5  2.663640       NaN       NaN>

In [15]:
df.ffill(limit = 2)

          0         1         2
0  0.983924  0.178441  0.573742
1 -2.001475 -0.987922 -0.378934
2 -1.198428 -0.987922 -0.804601
3  0.380425 -0.987922 -1.402965
4  0.976994       NaN -1.402965
5  2.663640       NaN -1.402965

In [16]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [17]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [21]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"], "k2": [1,1,2,3,3,4,4]})

In [22]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [23]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [25]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [26]:
data["v1"] = range(7)

In [27]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [29]:
data.drop_duplicates(subset = ["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [30]:
data.drop_duplicates(["k1", "k2"], keep = "last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [41]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon", "pastrami", "corned beef", "bacon", "pastrami", "honey ham", "nove lox"], "ounces": [4,3,12,6,7.5,8,3,5,6]})

In [42]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nove lox     6.0

In [34]:
meat_to_animal = {
    "bacon": "pig", 
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef":"pig",
    "nova lox" : "salmon"
}

In [35]:
data["animal"] = data["food"].map(meat_to_animal)

In [36]:
data

          food  ounces animal
0        bacon     4.0    pig
1  pulled pork     3.0    pig
2        bacon    12.0    pig
3     pastrami     6.0    cow
4  corned beef     7.5    pig
5        bacon     8.0    pig
6     pastrami     3.0    cow
7    honey ham     5.0    NaN
8     nove lox     6.0    NaN

In [52]:
def get_animal(x):
    return meat_to_animal.get(x, x)

In [53]:
data["food"].map(get_animal)

0          pig
1          pig
2          pig
3          cow
4          pig
5          pig
6          cow
7    honey ham
8     nove lox
Name: food, dtype: str

In [49]:
type(get_animal)

function

In [50]:
type(meat_to_animal)

dict