In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
from lxml import objectify

In [6]:
path = "datasets/mta_perf/Performance_MNR.xml"

In [7]:
frame = pd.read_csv("examples/ex1.csv")

In [8]:
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [9]:
frame.to_pickle("examples/frame_pickle")

In [10]:
pd.read_pickle("examples/frame_pickle")

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [12]:
xlsx = pd.ExcelFile("examples/ex1.xlsx")

In [13]:
xlsx.sheet_names

['Sheet1']

In [15]:
xlsx.parse(sheet_name = "Sheet1")

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [16]:
xlsx.parse(sheet_name = "Sheet1", index_col = 0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [17]:
frame = pd.read_excel("examples/ex1.xlsx", sheet_name = "Sheet1")

In [18]:
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [19]:
writer = pd.ExcelWriter("examples/ex2.xlsx")

In [22]:
frame.to_excel(writer, sheet_name = "Sheet1")

In [24]:
writer.close()

In [25]:
frame = pd.DataFrame({"a":np.random.standard_normal(100)})

In [26]:
store = pd.HDFStore("examples/mydata.h5")

In [27]:
store["obj1"] = frame

In [28]:
store["obj1_col"] = frame["a"]

In [29]:
store

<class 'pandas.HDFStore'>
File path: examples/mydata.h5

In [30]:
store["obj1"]

           a
0  -0.063299
1   1.423880
2  -1.289746
3  -0.456283
4  -1.467790
..       ...
95  0.004294
96 -1.611652
97  0.629621
98  0.123624
99 -0.205130

[100 rows x 1 columns]

In [31]:
store.put("obj2", frame, format="table")

In [32]:
store.select("obj2", where = ["index >= 10 and index <=15"])

           a
10  0.429038
11  1.033115
12 -1.039897
13  1.301809
14  1.036879
15 -0.666486

In [33]:
store.close()

In [38]:
frame.to_hdf("examples/mydata.h5", key ="obj3", format = "table")

In [39]:
pd.read_hdf("examples/mydata.h5", key="obj3", where = ["index<5"])

          a
0 -0.063299
1  1.423880
2 -1.289746
3 -0.456283
4 -1.467790

In [40]:
import os

In [41]:
os.remove("examples/mydata.h5")

In [42]:
import requests