In [34]:
import numpy as np

In [35]:
import pandas as pd

In [36]:
cat = {
    "a" : [1,5,9],
    "b" : [2,6,10],
    "c" : [3, 7, 11],
    "d" : [4, 8, 12],
    "message": ["hello", "world", "foo"]
}

In [37]:
df = pd.DataFrame(cat)

In [38]:
df.to_csv(r"C:\Users\Ahem\Desktop\pandas\examples\ex1.csv", index=False)
print("File created successfully!")

File created successfully!

In [39]:
df = pd.read_csv("examples/ex1.csv")

In [40]:
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [45]:
cat2 = {
    0 : [1,5,9],
    1 : [2,6,10],
    2: [3,7,11],
    3: [4,8,12],
    4: ["hello", "world", "foo"]
}

In [46]:
df = pd.DataFrame(cat2)

In [47]:
df.to_csv(r"C:\Users\Ahem\Desktop\pandas\examples\ex2.csv", index=False)

In [48]:
df = pd.read_csv("examples/ex2.csv")

In [49]:
df

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [50]:
pd.read_csv("examples/ex2.csv", names = ["a", "b", "c", "d", "message"])

   a   b   c   d message
0  0   1   2   3       4
1  1   2   3   4   hello
2  5   6   7   8   world
3  9  10  11  12     foo

In [51]:
df = df.drop(0)

In [52]:
pd.read_csv("examples/ex2.csv", names = ["a", "b", "c", "d", "message"])

   a   b   c   d message
0  0   1   2   3       4
1  1   2   3   4   hello
2  5   6   7   8   world
3  9  10  11  12     foo

In [62]:
parsed = pd.read_csv("examples/csv_mindex.csv", index_col = ["key1", "key2"])

In [63]:
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16