In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import sqlite3

In [4]:
query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20), c REAL, d INTEGER
);"""

In [5]:
con = sqlite3.connect("mydata.sqlite")

In [6]:
con.execute(query)

In [7]:
con.commit()

In [8]:
data = [("Atlanta", "Georgia", 1.23, 6),
        ("Tallahassee", "Florida", 2.6, 3),
        ("Sacramento", "California", 1.7, 5)]

In [9]:
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"

In [10]:
con.executemany(stmt, data)

In [11]:
con.commit()

In [15]:
cursor = con.execute("SELECT * FROM test")

In [16]:
rows = cursor.fetchall()

In [17]:
rows

[('Atlanta', 'Georgia', 1.23, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [18]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

In [19]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.23  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [20]:
import sqlalchemy as sqla

In [21]:
db = sqla.create_engine("sqlite:///mydata.sqlite")

In [22]:
pd.read_sql("SELECT * FROM test", db)

             a           b     c  d
0      Atlanta     Georgia  1.23  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5