In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [4]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [5]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [7]:
string_data

0    aardvark
1         NaN
2         NaN
3     avocado
dtype: str

In [8]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [9]:
float_data = pd.Series([1, 2, None], dtype = "float64")

In [10]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [11]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [12]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [13]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data = pd.DataFrame([[1.,6.5,3.],[1.,np.nan,np.nan],[np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [16]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [18]:
data.dropna(how = "all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [19]:
data[4] = np.nan

In [20]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [21]:
data.dropna(axis = "columns", how = "all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [22]:
df = pd.DataFrame(np.random.standard_normal((7,3)))

In [23]:
df.iloc[:4, 1] = np.nan

In [25]:
df.iloc[:2,2] = np.nan

In [26]:
df

          0         1         2
0  1.215051       NaN       NaN
1  0.237118       NaN       NaN
2  1.030821       NaN  0.836778
3 -0.717970       NaN  1.616526
4 -0.341939  0.164093 -0.542329
5 -0.809263 -0.571872 -1.295749
6  1.697541 -0.728149 -0.671134

In [27]:
df.dropna()

          0         1         2
4 -0.341939  0.164093 -0.542329
5 -0.809263 -0.571872 -1.295749
6  1.697541 -0.728149 -0.671134

In [28]:
df.dropna(thresh = 2)

          0         1         2
2  1.030821       NaN  0.836778
3 -0.717970       NaN  1.616526
4 -0.341939  0.164093 -0.542329
5 -0.809263 -0.571872 -1.295749
6  1.697541 -0.728149 -0.671134