In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [5]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [6]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [7]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [9]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [10]:
data.replace({-999: np.nan, -1000:np.nan})

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [12]:
data = pd.DataFrame(np.arange(12).reshape((3,4)), index = ["ohio", "colorado", "new york"], columns = ["one", "two", "three", "four"])

In [13]:
data

          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
new york    8    9     10    11

In [14]:
def transform(x):
    return x[:4].upper()

In [15]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='str')

In [16]:
data.index = data.index.map(transform)

In [17]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [18]:
data.rename(index = str.title, columns = str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [22]:
data.rename(index = {"OHIO":"indiana"}, columns = {"three":"peekaboo"})

         one  two  peekaboo  four
indiana    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [23]:
ages = [20, 22, 25, 27, 23, 37, 31, 61, 45, 41, 32]

In [24]:
bins = [18, 25, 35, 60, 100]

In [25]:
age_categories = pd.cut(ages, bins)