In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [5]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [6]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data = pd.Series(["aardvark", np.nan, None, "avacado"])

In [9]:
string_data

0    aardvark
1         NaN
2         NaN
3     avacado
dtype: str

In [10]:
float_data = pd.Series([1,2, None], dtype = "float64")

In [11]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [12]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [13]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [15]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [18]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [19]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [20]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [21]:
data.dropna(how = "all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [22]:
data[4] = np.nan

In [23]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [25]:
data.dropna(axis = "columns", how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [27]:
df = pd.DataFrame(np.random.standard_normal((7,3)))

In [28]:
df.iloc[:4,1] = np.nan

In [29]:
df.iloc[:2, 2] = np.nan

In [30]:
df

          0         1         2
0 -0.483329       NaN       NaN
1  0.890992       NaN       NaN
2  1.836544       NaN -0.282342
3  0.806580       NaN -0.274558
4  0.658088  0.025982  0.648196
5 -1.301300  0.341345  1.870639
6 -0.087139 -0.552713  0.097770

In [31]:
df.dropna()

          0         1         2
4  0.658088  0.025982  0.648196
5 -1.301300  0.341345  1.870639
6 -0.087139 -0.552713  0.097770

In [32]:
df.dropna(thresh = 2)

          0         1         2
2  1.836544       NaN -0.282342
3  0.806580       NaN -0.274558
4  0.658088  0.025982  0.648196
5 -1.301300  0.341345  1.870639
6 -0.087139 -0.552713  0.097770

In [33]:
df.fillna(0)

          0         1         2
0 -0.483329  0.000000  0.000000
1  0.890992  0.000000  0.000000
2  1.836544  0.000000 -0.282342
3  0.806580  0.000000 -0.274558
4  0.658088  0.025982  0.648196
5 -1.301300  0.341345  1.870639
6 -0.087139 -0.552713  0.097770

In [34]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7.])

In [35]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [40]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"], "k2": [1,1,2,3,4,4,4]})

In [37]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   4
5  two   4
6  two   5

In [41]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [42]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   4
5  two   4

In [43]:
data["v1"] = range(7)

In [44]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   4   4
5  two   4   5
6  two   4   6

In [45]:
data.drop_duplicates(subset = ["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [47]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [48]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [49]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [50]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64