In [3]:
import pandas as pd

In [4]:
data = {"state": ["ohio", "ohio", "ohio", "nevada", "nevada", "neveda"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [5]:
frame = pd.DataFrame(data)

In [6]:
frame

    state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9
5  neveda  2003  3.2

In [7]:
frame.head

<bound method NDFrame.head of     state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9
5  neveda  2003  3.2>

In [8]:
frame.tail

<bound method NDFrame.tail of     state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9
5  neveda  2003  3.2>

In [9]:
pd.DataFrame(data, columns = ["year", "state", "pop"])

   year   state  pop
0  2000    ohio  1.5
1  2001    ohio  1.7
2  2002    ohio  3.6
3  2001  nevada  2.4
4  2002  nevada  2.9
5  2003  neveda  3.2

In [10]:
frame2 = pd.DataFrame(data, columns = ["year", "state", "pop", "debt"])

In [11]:
frame2

   year   state  pop debt
0  2000    ohio  1.5  NaN
1  2001    ohio  1.7  NaN
2  2002    ohio  3.6  NaN
3  2001  nevada  2.4  NaN
4  2002  nevada  2.9  NaN
5  2003  neveda  3.2  NaN

In [12]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [13]:
frame2["state"]

0      ohio
1      ohio
2      ohio
3    nevada
4    nevada
5    neveda
Name: state, dtype: str

In [14]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [15]:
frame2.loc[1]

year     2001
state    ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [16]:
frame2.iloc[2]

year     2002
state    ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [17]:
frame2["debt"] = 16.5

In [18]:
frame2

   year   state  pop  debt
0  2000    ohio  1.5  16.5
1  2001    ohio  1.7  16.5
2  2002    ohio  3.6  16.5
3  2001  nevada  2.4  16.5
4  2002  nevada  2.9  16.5
5  2003  neveda  3.2  16.5

In [19]:
import numpy as np

In [20]:
frame2["dept"] = np.arange(6.)

In [21]:
frame2

   year   state  pop  debt  dept
0  2000    ohio  1.5  16.5   0.0
1  2001    ohio  1.7  16.5   1.0
2  2002    ohio  3.6  16.5   2.0
3  2001  nevada  2.4  16.5   3.0
4  2002  nevada  2.9  16.5   4.0
5  2003  neveda  3.2  16.5   5.0

In [22]:
val = pd.Series([-1.2, -1.5, -1.7], index = ["two", "four", "five"])

In [23]:
frame2["debt"] = val

In [24]:
frame2

   year   state  pop  debt  dept
0  2000    ohio  1.5   NaN   0.0
1  2001    ohio  1.7   NaN   1.0
2  2002    ohio  3.6   NaN   2.0
3  2001  nevada  2.4   NaN   3.0
4  2002  nevada  2.9   NaN   4.0
5  2003  neveda  3.2   NaN   5.0

In [25]:
frame2["eastern"] = frame2["state"] == "ohio"

In [26]:
frame2

   year   state  pop  debt  dept  eastern
0  2000    ohio  1.5   NaN   0.0     True
1  2001    ohio  1.7   NaN   1.0     True
2  2002    ohio  3.6   NaN   2.0     True
3  2001  nevada  2.4   NaN   3.0    False
4  2002  nevada  2.9   NaN   4.0    False
5  2003  neveda  3.2   NaN   5.0    False

In [27]:
del frame2["eastern"]

In [28]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'dept'], dtype='str')

In [32]:
del frame2["debt"]

In [33]:
frame2.columns

Index(['year', 'state', 'pop'], dtype='str')

In [34]:
frame2["dept"] = np.arange(6.)

In [35]:
frame2

   year   state  pop  dept
0  2000    ohio  1.5   0.0
1  2001    ohio  1.7   1.0
2  2002    ohio  3.6   2.0
3  2001  nevada  2.4   3.0
4  2002  nevada  2.9   4.0
5  2003  neveda  3.2   5.0

In [36]:
population = {"ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}, "nevada": {2001: 2.4, 2002: 2.9}}

In [38]:
frame3 = pd.DataFrame(population)

In [39]:
frame3

      ohio  nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [40]:
frame3.T

        2000  2001  2002
ohio     1.5   1.7   3.6
nevada   NaN   2.4   2.9

In [41]:
pd.DataFrame(population, index = [2001, 2002, 2003])

      ohio  nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [42]:
pdata = {"ohio": frame3["ohio"][:-1], "nevada": frame3["nevada"][:2]}

In [43]:
pd.DataFrame(pdata)

      ohio  nevada
2000   1.5     NaN
2001   1.7     2.4

In [44]:
frame3.index.name = "year"

In [45]:
frame3.columns.name = "state"

In [46]:
frame3

state  ohio  nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [47]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [48]:
frame2.to_numpy()

array([[2000, 'ohio', 1.5, 0.0],
       [2001, 'ohio', 1.7, 1.0],
       [2002, 'ohio', 3.6, 2.0],
       [2001, 'nevada', 2.4, 3.0],
       [2002, 'nevada', 2.9, 4.0],
       [2003, 'neveda', 3.2, 5.0]], dtype=object)