In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
a = pd.Series([np.nan, 3.5, 0.0, 3.5, 4.5, np.nan], index = ["f", "e", "d", "c", "b", "a"])

In [6]:
b = pd.Series([0., np.nan, 2., np.nan, np.nan, 5.], index = ["a", "b", "c", "d", "e", "f"])

In [7]:
a

f    NaN
e    3.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [8]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [9]:
np.where(pd.isna(a), b, a)

array([0. , 3.5, 0. , 3.5, 4.5, 5. ])

In [10]:
a.combine_first(b)

a    0.0
b    4.5
c    3.5
d    0.0
e    3.5
f    5.0
dtype: float64

In [12]:
df1 = pd.DataFrame({"a": [1., np.nan, 5., np.nan], "b": [np.nan, 2., np.nan, 6.], "c": range(2,18,4)})

In [13]:
df2 = pd.DataFrame({"a":[5., 4., np.nan, 3., 7.], "b":[np.nan, 3., 4., 6., 8.]})

In [14]:
df1

     a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [15]:
df2

     a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [16]:
df1.combine_first(df2)

     a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [18]:
data = pd.DataFrame(np.arange(6).reshape((2,3)), index = pd.Index(["ohio", "colorado"], name = "state"), columns = pd.Index(["one", "two", "three"], name= "number"))

In [19]:
data

number    one  two  three
state
ohio        0    1      2
colorado    3    4      5

In [20]:
result = data.stack()

In [21]:
result

state     number
ohio      one       0
          two       1
          three     2
colorado  one       3
          two       4
          three     5
dtype: int64

In [22]:
result.unstack()

number    one  two  three
state
ohio        0    1      2
colorado    3    4      5

In [23]:
result.unstack(level = 0)

state   ohio  colorado
number
one        0         3
two        1         4
three      2         5

In [24]:
s1 = pd.Series([0,1,2,3], index = ["a", "b", "c", "d"], dtype = "Int64")

In [25]:
s2 = pd.Series([4,5,6], index = ["c", "d", "e"], dtype = "Int64")

In [26]:
data2 = pd.concat([s1, s2], keys = ["one", "two"])

In [27]:
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [28]:
data2.unstack()

        a     b  c  d     e
one     0     1  2  3  <NA>
two  <NA>  <NA>  4  5     6

In [29]:
data2.unstack().stack()

one  a       0
     b       1
     c       2
     d       3
     e    <NA>
two  a    <NA>
     b    <NA>
     c       4
     d       5
     e       6
dtype: Int64

In [31]:
data = pd.read_csv("examples/macrodata.csv")

In [33]:
data = data[["year", "quarter", "realgdp", "infl", "unemp"]]

In [34]:
data.head()

   year  quarter   realgdp  infl  unemp
0  1959        1  2710.349  0.00    5.8
1  1959        2  2778.801  2.34    5.1
2  1959        3  2775.488  2.74    5.3
3  1959        4  2785.204  0.27    5.6
4  1960        1  2847.699  2.31    5.2

In [39]:
print(data.columns.tolist())

['quarter', 'realgdp', 'infl', 'unemp']