In [1]:
import pandas as pd

In [3]:
data = {"state": ["ohio", "ohio", "ohio", "nevada", "nevada", "neveda"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [4]:
frame = pd.DataFrame(data)

In [6]:
frame

    state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9
5  neveda  2003  3.2

In [7]:
frame.head

<bound method NDFrame.head of     state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9
5  neveda  2003  3.2>

In [8]:
frame.tail

<bound method NDFrame.tail of     state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9
5  neveda  2003  3.2>

In [11]:
pd.DataFrame(data, columns = ["year", "state", "pop"])

   year   state  pop
0  2000    ohio  1.5
1  2001    ohio  1.7
2  2002    ohio  3.6
3  2001  nevada  2.4
4  2002  nevada  2.9
5  2003  neveda  3.2

In [12]:
frame2 = pd.DataFrame(data, columns = ["year", "state", "pop", "debt"])

In [13]:
frame2

   year   state  pop debt
0  2000    ohio  1.5  NaN
1  2001    ohio  1.7  NaN
2  2002    ohio  3.6  NaN
3  2001  nevada  2.4  NaN
4  2002  nevada  2.9  NaN
5  2003  neveda  3.2  NaN

In [ ]:
frame