In [1]:
import numpy as np

In [2]:
import pandas as pd

In [9]:
left1 = pd.DataFrame({"key":["a", "b", "a", "a", "b", "c"], "value": pd.Series(range(6), dtype = "Int64")})

In [5]:
right1 = pd.DataFrame({"group_val": [3.4, 7]}, index = ["a", "b"])

In [6]:
left1

  key1  value
0    a      0
1    b      1
2    a      2
3    a      3
4    b      4
5    c      5

In [7]:
right1

   group_val
a        3.4
b        7.0

In [10]:
pd.merge(left1, right1, left_on = "key", right_index = True)

  key  value  group_val
0   a      0        3.4
1   b      1        7.0
2   a      2        3.4
3   a      3        3.4
4   b      4        7.0

In [11]:
pd.merge(left1, right1, left_on = "key", right_index = True, how = "outer")

  key  value  group_val
0   a      0        3.4
2   a      2        3.4
3   a      3        3.4
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [13]:
lefth = pd.DataFrame({"key1": ["ohio", "ohio", "ohio", "nevada", "nevada"], "key2": [2000, 2001, 2002, 2001, 2002], "data": pd.Series(range(5), dtype = "Int64")})

In [14]:
righth_index = pd.MultiIndex.from_arrays(
    [
        ["nevada", "nevada", "ohio", "ohio", "ohio", "ohio"], 
        [2001, 2002, 2000, 2000, 2001, 2002]
    ]
)

In [16]:
righth = pd.DataFrame({"event1": pd.Series([0,2,4,6,8,10], dtype = "Int64", index = righth_index), "event2": pd.Series([1,3,5,7,9,11], dtype = "Int64", index = righth_index)})

In [17]:
lefth

     key1  key2  data
0    ohio  2000     0
1    ohio  2001     1
2    ohio  2002     2
3  nevada  2001     3
4  nevada  2002     4

In [18]:
righth

             event1  event2
nevada 2001       0       1
       2002       2       3
ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [19]:
pd.merge(lefth, righth, left_on = ["key1","key2"], right_index=True)

     key1  key2  data  event1  event2
0    ohio  2000     0       4       5
0    ohio  2000     0       6       7
1    ohio  2001     1       8       9
2    ohio  2002     2      10      11
3  nevada  2001     3       0       1
4  nevada  2002     4       2       3

In [20]:
pd.merge(lefth, righth, left_on = ["key1", "key2"], right_index = True, how="outer")

     key1  key2  data  event1  event2
3  nevada  2001     3       0       1
4  nevada  2002     4       2       3
0    ohio  2000     0       4       5
0    ohio  2000     0       6       7
1    ohio  2001     1       8       9
2    ohio  2002     2      10      11

In [21]:
left2 = pd.DataFrame([[1., 2.],[3.,4.],[5.,6.]], index = ["a", "c", "e"], columns = ["ohio", "nevada"]).astype("Int64")

In [22]:
right2 = pd.DataFrame([[7.,8.],[9.,10.],[11.,12.], [13.,14.]], index = ["b", "c", "d", "e"], columns = ["missouri", "alabama"]).astype("Int64")

In [23]:
left2

   ohio  nevada
a     1       2
c     3       4
e     5       6

In [24]:
right2

   missouri  alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [25]:
pd.merge(left2, right2, how = "outer", left_index = True, right_index = True)

   ohio  nevada  missouri  alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [26]:
left2.join(right2, how = "outer")

   ohio  nevada  missouri  alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [27]:
left1.join(right1, on = "key")

  key  value  group_val
0   a      0        3.4
1   b      1        7.0
2   a      2        3.4
3   a      3        3.4
4   b      4        7.0
5   c      5        NaN

In [28]:
another = pd.DataFrame([[7.,8.],[9.,10.],[11., 12.], [16.,17.]], index=["a", "c","e","f"], columns = ["new york", "oregon"])

In [29]:
another

   new york  oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [30]:
left2.join([right2, another])

   ohio  nevada  missouri  alabama  new york  oregon
a     1       2      <NA>     <NA>       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        13       14      11.0    12.0

In [31]:
left2.join([right2, another], how = "outer")

   ohio  nevada  missouri  alabama  new york  oregon
a     1       2      <NA>     <NA>       7.0     8.0
b  <NA>    <NA>         7        8       NaN     NaN
c     3       4         9       10       9.0    10.0
d  <NA>    <NA>        11       12       NaN     NaN
e     5       6        13       14      11.0    12.0
f  <NA>    <NA>      <NA>     <NA>      16.0    17.0