In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
df = pd.DataFrame({"key1":["a", "a", None, "b", "b", "a", None], "key2": pd.Series([1,2,1,2,1,None,1], dtype = "Int64"), "data1":np.random.standard_normal(7), "data2":np.random.standard_normal(7)})

In [5]:
df

  key1  key2     data1     data2
0    a     1 -1.059716 -1.166126
1    a     2  1.006023 -1.005357
2  NaN     1 -0.968942  0.357000
3    b     2 -1.644661 -0.579762
4    b     1 -1.512817  0.356619
5    a  <NA> -0.274028 -1.189782
6  NaN     1 -0.070168 -0.074929

In [9]:
grouped = df["data1"].groupby(df["key1"])

In [10]:
grouped

In [11]:
grouped.mean()

key1
a   -0.109240
b   -1.578739
Name: data1, dtype: float64

In [12]:
means = df["data1"].groupby([df["key1"], df["key2"]]).mean()
means

key1  key2
a     1      -1.059716
      2       1.006023
b     1      -1.512817
      2      -1.644661
Name: data1, dtype: float64

In [15]:
means.unstack()

key2         1         2
key1
a    -1.059716  1.006023
b    -1.512817 -1.644661

In [16]:
states = np.array(["OH", "CA", "CA", "OH", "OH","CA", "OH"])
years = [2005, 2005, 2006, 2005, 2006, 2005, 2006]
df["data1"].groupby([states, years]).mean()

CA  2005    0.365998
    2006   -0.968942
OH  2005   -1.352188
    2006   -0.791492
Name: data1, dtype: float64

In [22]:
df.groupby("key1").mean()

      key2     data1     data2
key1
a      1.5 -0.109240 -1.120422
b      1.5 -1.578739 -0.111572

In [26]:
df.groupby("key2").mean()

TypeError: dtype 'str' does not support operation 'mean'

In [19]:
df.groupby(["key1", "key2"]).mean()

              data1     data2
key1 key2
a    1    -1.059716 -1.166126
     2     1.006023 -1.005357
b    1    -1.512817  0.356619
     2    -1.644661 -0.579762

In [27]:
df.groupby(["key1", "key2"]).size()

key1  key2
a     1       1
      2       1
b     1       1
      2       1
dtype: int64

In [28]:
df.groupby("key1", dropna = False).size()

key1
a      3
b      2
NaN    2
dtype: int64

In [29]:
df.groupby("key1").count()

      key2  data1  data2
key1
a        2      3      3
b        2      2      2