In [1]:
import numpy as np

In [2]:
import pandas as pd

In [7]:
data = pd.Series(np.random.uniform(size = 9), index = [["a", "a", "a", "b", "b", "c", "c", "d", "d"], [1,2,3,1,3,1,2,2,3]])

In [8]:
data

a  1    0.005046
   2    0.536333
   3    0.462940
b  1    0.686331
   3    0.564619
c  1    0.815660
   2    0.847416
d  2    0.600784
   3    0.458397
dtype: float64

In [9]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [10]:
data["b"]

1    0.686331
3    0.564619
dtype: float64

In [11]:
data["b":"c"]

b  1    0.686331
   3    0.564619
c  1    0.815660
   2    0.847416
dtype: float64

In [12]:
data.loc[["b", "d"]]

b  1    0.686331
   3    0.564619
d  2    0.600784
   3    0.458397
dtype: float64

In [13]:
data.loc[:,2]

a    0.536333
c    0.847416
d    0.600784
dtype: float64

In [14]:
data.unstack()

          1         2         3
a  0.005046  0.536333  0.462940
b  0.686331       NaN  0.564619
c  0.815660  0.847416       NaN
d       NaN  0.600784  0.458397

In [15]:
data.unstack().stack()

a  1    0.005046
   2    0.536333
   3    0.462940
b  1    0.686331
   2         NaN
   3    0.564619
c  1    0.815660
   2    0.847416
   3         NaN
d  1         NaN
   2    0.600784
   3    0.458397
dtype: float64

In [17]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)), index = [["a", "a", "b", "b"], [1,2,1,2]], columns = [["ohio", "ohio", "colorado"],["green", "red", "green"]])

In [18]:
frame

     ohio     colorado
    green red    green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [20]:
frame.index.names = ["key1", "key2"]

In [21]:
frame.columns.names = ["state", "color"]

In [22]:
frame

state      ohio     colorado
color     green red    green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [23]:
frame.index.nlevels

2

In [24]:
frame["ohio"]

color      green  red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [25]:
pd.MultiIndex.from_arrays([["ohio", "ohio", "colorado"], ["green", "red", "green"]], names = ["state", "color"])

MultiIndex([(    'ohio', 'green'),
            (    'ohio',   'red'),
            ('colorado', 'green')],
           names=['state', 'color'])

In [26]:
frame.swaplevel("key1", "key2")

state      ohio     colorado
color     green red    green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [27]:
frame.sort_index(level = 1)

state      ohio     colorado
color     green red    green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [28]:
frame.swaplevel(0,1).sort_index(level=0)

state      ohio     colorado
color     green red    green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [29]:
frame.groupby(level = "key2").sum()

state  ohio     colorado
color green red    green
key2
1         6   8       10
2        12  14       16

In [32]:
frame.T.groupby(level="color").sum().T

color      green  red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [34]:
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1), "c":["one", "one", "one", "two", "two", "two","two"], "d":[0,1,2,0,1,2,3]})

In [35]:
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [36]:
frame2 = frame.set_index(["c", "d"])

In [37]:
frame2

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [38]:
frame.set_index(["c", "d"], drop=False)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [39]:
frame2.reset_index()

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1