In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({"key" : ["b", "b", "a", "c", "a", "b"], "data1": range(6)})

In [5]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [6]:
pd.get_dummies(df["key"])

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [9]:
dummies = pd.get_dummies(df["key"], prefix = "key")

In [10]:
df_with_dummies = df[["data1"]].join(dummies)

In [11]:
df_with_dummies

   data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [17]:
s = pd.Series([1,2,3,None])

In [18]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [19]:
s.dtype

dtype('float64')

In [20]:
s = pd.Series([1,2,3,None], dtype = pd.Int64Dtype())

In [21]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [22]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [24]:
s.dtype

Int64Dtype()

In [25]:
s[3]

In [26]:
s[3] is pd.NA

True

In [27]:
s = pd.Series([1,2,3,None], dtype = "Int64")

In [28]:
s = pd.Series(['one', 'two', None, 'three'], dtype = pd.StringDtype())

In [29]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [31]:
df = pd.DataFrame({"a" : [1,2,None,4],
                   "b": ["one", "two", "three", None],
                   "c": [False, None, False, True]})

In [32]:
df

     a      b      c
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0    NaN   True

In [34]:
df["a"] = df["a"].astype("Int64")

In [35]:
df["b"] = df["b"].astype("string")

In [36]:
df["c"] = df["c"].astype("boolean")

In [37]:
df

      a      b      c
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

In [38]:
val = "a,b,  guidio"

In [39]:
val.split(",")

['a', 'b', '  guidio']

In [43]:
"guidio" in val

True

In [44]:
val.index(",")

1

In [45]:
val.find(":")

-1

In [46]:
val.index(":")

ValueError: substring not found

In [47]:
val.count(",")

2

In [50]:
val.replace(",", "::")

'a::b::  guidio'

In [51]:
val.replace(",", "")

'ab  guidio'