In [1]:
import numpy as np

In [2]:
import pandas as pd

In [9]:
tips = pd.read_csv("examples/tips.csv")

In [21]:
tips["tip_pct"] = tips["tip"]/tips["total_bill"]

In [22]:
def top(df, n = 5, column = "tip_pct"):
    return df.sort_values(column, ascending=False)[:n]

In [23]:
top(tips, n = 6)

     total_bill   tip smoker  day    time  size   tip_pct
172        7.25  5.15    Yes  Sun  Dinner     2  0.710345
178        9.60  4.00    Yes  Sun  Dinner     2  0.416667
67         3.07  1.00    Yes  Sat  Dinner     1  0.325733
232       11.61  3.39     No  Sat  Dinner     2  0.291990
183       23.17  6.50    Yes  Sun  Dinner     4  0.280535
109       14.31  4.00    Yes  Sat  Dinner     2  0.279525

In [26]:
tips.groupby("smoker").apply(top)

            total_bill   tip   day    time  size   tip_pct
smoker
No     232       11.61  3.39   Sat  Dinner     2  0.291990
       149        7.51  2.00  Thur   Lunch     2  0.266312
       51        10.29  2.60   Sun  Dinner     2  0.252672
       185       20.69  5.00   Sun  Dinner     5  0.241663
       88        24.71  5.85  Thur   Lunch     2  0.236746
Yes    172        7.25  5.15   Sun  Dinner     2  0.710345
       178        9.60  4.00   Sun  Dinner     2  0.416667
       67         3.07  1.00   Sat  Dinner     1  0.325733
       183       23.17  6.50   Sun  Dinner     4  0.280535
       109       14.31  4.00   Sat  Dinner     2  0.279525

In [27]:
tips.groupby(["smoker", "day"]).apply(top, n=1, column="total_bill")

                 total_bill    tip    time  size   tip_pct
smoker day
No     Fri  94        22.75   3.25  Dinner     2  0.142857
       Sat  212       48.33   9.00  Dinner     4  0.186220
       Sun  156       48.17   5.00  Dinner     6  0.103799
       Thur 142       41.19   5.00   Lunch     5  0.121389
Yes    Fri  95        40.17   4.73  Dinner     4  0.117750
       Sat  170       50.81  10.00  Dinner     3  0.196812
       Sun  182       45.35   3.50  Dinner     3  0.077178
       Thur 197       43.11   5.00   Lunch     4  0.115982

In [28]:
result = tips.groupby("smoker")["tip_pct"].describe()

In [29]:
result

,count,mean,std,min,25%,50%,75%,max
smoker,,,,,,,,
No,151.0,0.159328,0.039910,0.056797,0.136906,0.155625,0.185014,0.291990
Yes,93.0,0.163196,0.085119,0.035638,0.106771,0.153846,0.195059,0.710345

In [30]:
result.unstack("smoker")

       smoker
count  No        151.000000
       Yes        93.000000
mean   No          0.159328
       Yes         0.163196
std    No          0.039910
       Yes         0.085119
min    No          0.056797
       Yes         0.035638
25%    No          0.136906
       Yes         0.106771
50%    No          0.155625
       Yes         0.153846
75%    No          0.185014
       Yes         0.195059
max    No          0.291990
       Yes         0.710345
dtype: float64

In [33]:
tips.groupby("smoker", group_keys = False).apply(top)

     total_bill   tip   day    time  size   tip_pct
232       11.61  3.39   Sat  Dinner     2  0.291990
149        7.51  2.00  Thur   Lunch     2  0.266312
51        10.29  2.60   Sun  Dinner     2  0.252672
185       20.69  5.00   Sun  Dinner     5  0.241663
88        24.71  5.85  Thur   Lunch     2  0.236746
172        7.25  5.15   Sun  Dinner     2  0.710345
178        9.60  4.00   Sun  Dinner     2  0.416667
67         3.07  1.00   Sat  Dinner     1  0.325733
183       23.17  6.50   Sun  Dinner     4  0.280535
109       14.31  4.00   Sat  Dinner     2  0.279525