In [1]:
import numpy as np

In [3]:
import pandas as pd

In [5]:
people = pd.DataFrame(np.random.standard_normal((5,5)), columns = ["a", "b", "c", "d", "e"], index = ["Joe", "Steve", "Wanda", "Jill", "Trey"])

In [6]:
people.iloc[2:3, [1,3]] = np.nan

In [7]:
people

              a         b         c         d         e
Joe   -0.047955  0.569724 -0.688252  0.105167  0.434965
Steve  0.051780  0.509255  0.247200 -0.372807  0.292487
Wanda -0.281960       NaN  0.094331       NaN  0.900714
Jill  -1.105068  0.637319 -0.561330 -1.198553 -2.643024
Trey   1.562954 -0.425255 -0.493131 -0.047957 -0.384614

In [8]:
mapping = {"a": "red", "b":"red", "c": "blue", "d": "blue", "e": "red", "f": "orange"}

In [13]:
by_column = people.T.groupby(mapping).sum().T

In [16]:
by_column

           blue       red
Joe   -0.583085  0.956734
Steve -0.125608  0.853523
Wanda  0.094331  0.618754
Jill  -1.759883 -3.110773
Trey  -0.541089  0.753086

In [17]:
map_series = pd.Series(mapping)

In [18]:
map_series

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: str

In [20]:
people.T.groupby(map_series).count().T

       blue  red
Joe       2    3
Steve     2    3
Wanda     1    2
Jill      2    3
Trey      2    3

In [21]:
people.groupby(len).sum()

          a         b         c         d         e
3 -0.047955  0.569724 -0.688252  0.105167  0.434965
4  0.457887  0.212064 -1.054462 -1.246510 -3.027638
5 -0.230179  0.509255  0.341530 -0.372807  1.193201

In [22]:
key_list = ["one", "one", "one", "two", "two"]

In [23]:
people.groupby([len, key_list]).min()

              a         b         c         d         e
3 one -0.047955  0.569724 -0.688252  0.105167  0.434965
4 two -1.105068 -0.425255 -0.561330 -1.198553 -2.643024
5 one -0.281960  0.509255  0.094331 -0.372807  0.292487

In [24]:
columns = pd.MultiIndex.from_arrays([["US", "US", "US", "JP", "JP"], [1,3,5,1,3]], names=["city","tenor"])

In [25]:
hier_df = pd.DataFrame(np.random.standard_normal((4,5)), columns = columns)

In [26]:
hier_df

city         US                            JP
tenor         1         3         5         1         3
0      2.487758  0.785439  0.230702  1.027881 -1.505651
1      0.370265 -0.833244  0.559764  0.250152  1.094911
2      0.503036  0.745146 -0.597541  0.245215 -0.645629
3     -0.345818 -0.496929  0.423166  0.734456  0.168193

In [28]:
hier_df.T.groupby(level="city").count().T

city  JP  US
0      2   3
1      2   3
2      2   3
3      2   3

In [30]:
tips = pd.read_csv("examples/tips.csv")

In [31]:
tips.head()

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

In [32]:
tips["tip_pct"] = tips["tip"] / tips["total_bill"]

In [33]:
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [34]:
grouped = tips.groupby(["day", "smoker"])

In [36]:
grouped_pct = grouped["tip_pct"]

In [37]:
grouped_pct.agg("mean")

day   smoker
Fri   No        0.151650
      Yes       0.174783
Sat   No        0.158048
      Yes       0.147906
Sun   No        0.160113
      Yes       0.187250
Thur  No        0.160298
      Yes       0.163863
Name: tip_pct, dtype: float64

In [39]:
def peak_to_peak(arr):
    return arr.max() - arr.min()

In [40]:
grouped_pct.agg(["mean", "std", peak_to_peak])

                 mean       std  peak_to_peak
day  smoker
Fri  No      0.151650  0.028123      0.067349
     Yes     0.174783  0.051293      0.159925
Sat  No      0.158048  0.039767      0.235193
     Yes     0.147906  0.061375      0.290095
Sun  No      0.160113  0.042347      0.193226
     Yes     0.187250  0.154134      0.644685
Thur No      0.160298  0.038774      0.193350
     Yes     0.163863  0.039389      0.151240

In [41]:
grouped_pct.agg([("average", "mean"), ("stdev", np.std)])

              average     stdev
day  smoker
Fri  No      0.151650  0.024355
     Yes     0.174783  0.049553
Sat  No      0.158048  0.039323
     Yes     0.147906  0.060640
Sun  No      0.160113  0.041974
     Yes     0.187250  0.150023
Thur No      0.160298  0.038341
     Yes     0.163863  0.038213

In [42]:
functions = ["count", "mean", "max"]

In [43]:
result = grouped[["tip_pct", "total_bill"]].agg(functions)

In [44]:
result

            tip_pct                     total_bill
              count      mean       max      count       mean    max
day  smoker
Fri  No           4  0.151650  0.187735          4  18.420000  22.75
     Yes         15  0.174783  0.263480         15  16.813333  40.17
Sat  No          45  0.158048  0.291990         45  19.661778  48.33
     Yes         42  0.147906  0.325733         42  21.276667  50.81
Sun  No          57  0.160113  0.252672         57  20.506667  48.17
     Yes         19  0.187250  0.710345         19  24.120000  45.35
Thur No          45  0.160298  0.266312         45  17.113111  41.19
     Yes         17  0.163863  0.241255         17  19.190588  43.11

In [45]:
result["tip_pct"]

             count      mean       max
day  smoker
Fri  No          4  0.151650  0.187735
     Yes        15  0.174783  0.263480
Sat  No         45  0.158048  0.291990
     Yes        42  0.147906  0.325733
Sun  No         57  0.160113  0.252672
     Yes        19  0.187250  0.710345
Thur No         45  0.160298  0.266312
     Yes        17  0.163863  0.241255

In [46]:
ftuples = [("Average", "mean"), ("Variance", np.var)]

In [47]:
grouped[["tip_pct", "total_bill"]].agg(ftuples)

              tip_pct           total_bill
              Average  Variance    Average    Variance
day  smoker
Fri  No      0.151650  0.000593  18.420000   19.197250
     Yes     0.174783  0.002456  16.813333   77.058276
Sat  No      0.158048  0.001546  19.661778   78.133210
     Yes     0.147906  0.003677  21.276667   98.973546
Sun  No      0.160113  0.001762  20.506667   64.940331
     Yes     0.187250  0.022507  24.120000  103.306779
Thur No      0.160298  0.001470  17.113111   58.300079
     Yes     0.163863  0.001460  19.190588   65.702135

In [48]:
grouped.agg({"tip": np.max, "size":"sum"})

               tip  size
day  smoker
Fri  No       3.50     9
     Yes      4.73    31
Sat  No       9.00   115
     Yes     10.00   104
Sun  No       6.00   167
     Yes      6.50    49
Thur No       6.70   112
     Yes      5.00    40

In [49]:
grouped.agg({"tip_pct": ["min", "max", "mean", "std"], "size": "sum"})

              tip_pct                               size
                  min       max      mean       std  sum
day  smoker
Fri  No      0.120385  0.187735  0.151650  0.028123    9
     Yes     0.103555  0.263480  0.174783  0.051293   31
Sat  No      0.056797  0.291990  0.158048  0.039767  115
     Yes     0.035638  0.325733  0.147906  0.061375  104
Sun  No      0.059447  0.252672  0.160113  0.042347  167
     Yes     0.065660  0.710345  0.187250  0.154134   49
Thur No      0.072961  0.266312  0.160298  0.038774  112
     Yes     0.090014  0.241255  0.163863  0.039389   40