In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
obj = pd.Series(np.arange(3), index = ["a", "b", "c"])

In [5]:
index = obj.index

In [6]:
index

Index(['a', 'b', 'c'], dtype='str')

In [7]:
index[1] = "d"

TypeError: Index does not support mutable operations

In [8]:
labels = pd.Index(np.arange(3))

In [9]:
labels

Index([0, 1, 2], dtype='int64')

In [10]:
obj2 = pd.Series([1.5,-2.5,0], index = labels)

In [11]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [12]:
obj2.index is labels

True

In [13]:
populations = {"ohio": {2000:1.5, 2001: 1.7, 2002: 3.6}, "nevada": {2001: 2.4, 2002: 2.9}}

In [14]:
frame3 = pd.DataFrame(populations)

In [15]:
frame3

      ohio  nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [18]:
frame3.index.name = "year"

In [21]:
frame3.columns.name = "state"

In [22]:
frame3

state  ohio  nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [24]:
frame3.columns

Index(['ohio', 'nevada'], dtype='str', name='state')

In [25]:
"ohio" in frame3.columns

True

In [26]:
2003 in frame3.index

False

In [27]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='str')

In [28]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ["d", "b", "a", "c"])

In [29]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [30]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])

In [31]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [32]:
obj3 = pd.Series(["blue", "purple", "yellow"], index = [0,2,3])

In [33]:
obj3

0      blue
2    purple
3    yellow
dtype: str

In [34]:
obj3.reindex(np.arange(6), method = "ffill")

0      blue
1      blue
2    purple
3    yellow
4    yellow
5    yellow
dtype: str

In [35]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index = ["a", "c", "d"], columns = ["ohio", "texas", "california"])

In [36]:
frame

   ohio  texas  california
a     0      1           2
c     3      4           5
d     6      7           8

In [37]:
frame2 = frame.reindex(index = ["a", "b", "c", "d"])

In [38]:
frame2

   ohio  texas  california
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [39]:
states = ["texas", "utah", "california"]

In [40]:
frame.reindex(columns = states)

   texas  utah  california
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [41]:
frame.reindex(states, axis = "columns")

   texas  utah  california
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [42]:
frame.loc[["a","d", "c"],["california", "texas"]]

   california  texas
a           2      1
d           8      7
c           5      4