In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
frame = pd.DataFrame({"data1": np.random.standard_normal(1000),
                      "data2": np.random.standard_normal(1000)})

In [5]:
frame.head

<bound method NDFrame.head of         data1     data2
0   -1.352970  0.375411
1   -0.615290 -0.773624
2    0.083368 -0.888787
3   -0.155742 -0.583654
4   -0.173738  0.693009
..        ...       ...
995 -0.489876 -0.486971
996 -0.519633 -1.024641
997  0.071849 -0.789780
998  0.122577  1.246959
999  1.013173 -1.095471

[1000 rows x 2 columns]>

In [6]:
quartiles = pd.cut(frame["data1"], 4)

In [7]:
quartiles.head(10)

0    (-1.563, -0.0172]
1    (-1.563, -0.0172]
2     (-0.0172, 1.529]
3    (-1.563, -0.0172]
4    (-1.563, -0.0172]
5    (-1.563, -0.0172]
6     (-0.0172, 1.529]
7     (-0.0172, 1.529]
8     (-0.0172, 1.529]
9     (-0.0172, 1.529]
Name: data1, dtype: category
Categories (4, interval[float64, right]): [(-3.115, -1.563] < (-1.563, -0.0172] < (-0.0172, 1.529] < (1.529, 3.075]]

In [9]:
def get_stats(group):
    return pd.DataFrame(
        {"min": group.min(), "max":group.max(),
         "count": group.count(), "mean": group.mean()})

In [10]:
grouped = frame.groupby(quartiles)

In [11]:
grouped.apply(get_stats)

                              min       max  count      mean
data1
(-3.115, -1.563]  data1 -3.108986 -1.595391     54 -2.033454
                  data2 -2.196437  2.218919     54  0.050307
(-1.563, -0.0172] data1 -1.559513 -0.018361    455 -0.617205
                  data2 -2.403412  3.898705    455 -0.032960
(-0.0172, 1.529]  data1 -0.016537  1.525664    433  0.655333
                  data2 -3.138433  2.879108    433  0.071771
(1.529, 3.075]    data1  1.528970  3.074578     58  1.986071
                  data2 -2.703138  3.312544     58  0.119789

In [12]:
grouped.agg(["min", "max", "count", "mean"])

                      data1                               data2            \
                        min       max count      mean       min       max
data1
(-3.115, -1.563]  -3.108986 -1.595391    54 -2.033454 -2.196437  2.218919
(-1.563, -0.0172] -1.559513 -0.018361   455 -0.617205 -2.403412  3.898705
(-0.0172, 1.529]  -0.016537  1.525664   433  0.655333 -3.138433  2.879108
(1.529, 3.075]     1.528970  3.074578    58  1.986071 -2.703138  3.312544


                  count      mean
data1
(-3.115, -1.563]     54  0.050307
(-1.563, -0.0172]   455 -0.032960
(-0.0172, 1.529]    433  0.071771
(1.529, 3.075]       58  0.119789

In [13]:
quartiles_samp = pd.qcut(frame["data1"], 4, labels = False)

In [14]:
quartiles_samp.head()

0    0
1    1
2    2
3    1
4    1
Name: data1, dtype: int64

In [16]:
grouped = frame.groupby(quartiles_samp)

In [17]:
grouped.apply(get_stats)

                  min       max  count      mean
data1
0     data1 -3.108986 -0.633077    250 -1.249914
      data2 -2.403412  2.330045    250  0.010743
1     data1 -0.620903 -0.034552    250 -0.311646
      data2 -2.385459  3.898705    250 -0.059555
2     data1 -0.033394  0.732068    250  0.307884
      data2 -2.813716  2.879108    250  0.068752
3     data1  0.733458  3.074578    250  1.286942
      data2 -3.138433  3.312544    250  0.083039

In [18]:
s = pd.Series(np.random.standard_normal(6))

In [19]:
s[::2] = np.nan

In [20]:
s

0         NaN
1    0.437297
2         NaN
3    1.450883
4         NaN
5    0.195913
dtype: float64

In [21]:
s.fillna(s.mean())

0    0.694698
1    0.437297
2    0.694698
3    1.450883
4    0.694698
5    0.195913
dtype: float64

In [22]:
states = ["ohio", "new york", "vermont", "floride", "oregon", "neveda", "california", "idaho"]

In [24]:
group_key = ["east", "east", "east", "east", "west", "west", "west", "west"]

In [25]:
data = pd.Series(np.random.standard_normal(8), index = states)

In [26]:
data

ohio         -0.568361
new york      0.674910
vermont       1.024152
floride      -1.045801
oregon       -0.483820
neveda       -0.673464
california    0.160770
idaho         0.593862
dtype: float64

In [27]:
data[["vermont", "neveda", "idaho"]] = np.nan

In [28]:
data

ohio         -0.568361
new york      0.674910
vermont            NaN
floride      -1.045801
oregon       -0.483820
neveda             NaN
california    0.160770
idaho              NaN
dtype: float64

In [29]:
data.groupby(group_key).size()

east    4
west    4
dtype: int64

In [31]:
data.groupby(group_key).count()

east    3
west    2
dtype: int64

In [32]:
data.groupby(group_key).mean()

east   -0.313084
west   -0.161525
dtype: float64

In [33]:
def fill_mean(group):
    return group.fillna(group.mean())

In [34]:
data.groupby(group_key).apply(fill_mean)

east  ohio         -0.568361
      new york      0.674910
      vermont      -0.313084
      floride      -1.045801
west  oregon       -0.483820
      neveda       -0.161525
      california    0.160770
      idaho        -0.161525
dtype: float64

In [35]:
fill_values = {"east":0.5, "west":-1}

In [36]:
def fill_func(group):
    return group.fillna(fill_values[group.name])

In [37]:
data.groupby(group_key).apply(fill_func)

east  ohio         -0.568361
      new york      0.674910
      vermont       0.500000
      floride      -1.045801
west  oregon       -0.483820
      neveda       -1.000000
      california    0.160770
      idaho        -1.000000
dtype: float64