In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from datetime import datetime

In [4]:
dates = pd.date_range("2000-01-01", periods = 100)

In [6]:
ts = pd.Series(np.random.standard_normal(len(dates)), index = dates)

In [7]:
ts

2000-01-01    1.595966
2000-01-02    0.051955
2000-01-03    0.481531
2000-01-04    0.190682
2000-01-05   -0.601139
                ...
2000-04-05    2.466722
2000-04-06    0.411059
2000-04-07    0.106714
2000-04-08   -0.047175
2000-04-09   -0.304655
Freq: D, Length: 100, dtype: float64

In [9]:
ts.resample("ME").mean()

2000-01-31    0.030673
2000-02-29   -0.118438
2000-03-31   -0.012103
2000-04-30   -0.218760
Freq: ME, dtype: float64

In [12]:
ts.resample("ME").mean().to_period("M")

2000-01    0.030673
2000-02   -0.118438
2000-03   -0.012103
2000-04   -0.218760
Freq: M, dtype: float64

In [14]:
dates = pd.date_range("2000-01-01", periods = 12, freq="min")

In [15]:
ts = pd.Series(np.arange(len(dates)), index = dates)

In [16]:
ts

2000-01-01 00:00:00     0
2000-01-01 00:01:00     1
2000-01-01 00:02:00     2
2000-01-01 00:03:00     3
2000-01-01 00:04:00     4
2000-01-01 00:05:00     5
2000-01-01 00:06:00     6
2000-01-01 00:07:00     7
2000-01-01 00:08:00     8
2000-01-01 00:09:00     9
2000-01-01 00:10:00    10
2000-01-01 00:11:00    11
Freq: min, dtype: int64

In [17]:
ts.resample("5min").sum()

2000-01-01 00:00:00    10
2000-01-01 00:05:00    35
2000-01-01 00:10:00    21
Freq: 5min, dtype: int64

In [19]:
ts.resample("5min", closed="right", label = "right").sum()

2000-01-01 00:00:00     0
2000-01-01 00:05:00    15
2000-01-01 00:10:00    40
2000-01-01 00:15:00    11
Freq: 5min, dtype: int64

In [20]:
from pandas.tseries.frequencies import to_offset

In [21]:
result = ts.resample("5min", closed="right", label="right").sum()

In [22]:
result.index = result.index + to_offset("-1s")

In [23]:
result

1999-12-31 23:59:59     0
2000-01-01 00:04:59    15
2000-01-01 00:09:59    40
2000-01-01 00:14:59    11
Freq: 5min, dtype: int64

In [26]:
ts = pd.Series(np.random.permutation(np.arange(len(dates))), index = dates)

In [27]:
ts.resample("5min").ohlc()

                     open  high  low  close
2000-01-01 00:00:00    10    10    0      0
2000-01-01 00:05:00     7     7    1      1
2000-01-01 00:10:00    11    11    2      2

In [28]:
frame = pd.DataFrame(np.random.standard_normal((2,4)), index = pd.date_range("2000-01-01", periods = 2, freq = "W-WED"), columns = ["Colorado", "Texas", "New York", "Ohio"])

In [29]:
frame

            Colorado     Texas  New York      Ohio
2000-01-05  0.143061 -1.661158  0.673409  0.259948
2000-01-12  0.237462 -0.893170 -0.772092 -0.128398

In [30]:
df_daily = frame.resample("D").asfreq()

In [32]:
df_daily

            Colorado     Texas  New York      Ohio
2000-01-05  0.143061 -1.661158  0.673409  0.259948
2000-01-06       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN
2000-01-08       NaN       NaN       NaN       NaN
2000-01-09       NaN       NaN       NaN       NaN
2000-01-10       NaN       NaN       NaN       NaN
2000-01-11       NaN       NaN       NaN       NaN
2000-01-12  0.237462 -0.893170 -0.772092 -0.128398

In [33]:
frame.resample("D").ffill()

            Colorado     Texas  New York      Ohio
2000-01-05  0.143061 -1.661158  0.673409  0.259948
2000-01-06  0.143061 -1.661158  0.673409  0.259948
2000-01-07  0.143061 -1.661158  0.673409  0.259948
2000-01-08  0.143061 -1.661158  0.673409  0.259948
2000-01-09  0.143061 -1.661158  0.673409  0.259948
2000-01-10  0.143061 -1.661158  0.673409  0.259948
2000-01-11  0.143061 -1.661158  0.673409  0.259948
2000-01-12  0.237462 -0.893170 -0.772092 -0.128398

In [34]:
frame.resample("D").ffill(limit=2)

            Colorado     Texas  New York      Ohio
2000-01-05  0.143061 -1.661158  0.673409  0.259948
2000-01-06  0.143061 -1.661158  0.673409  0.259948
2000-01-07  0.143061 -1.661158  0.673409  0.259948
2000-01-08       NaN       NaN       NaN       NaN
2000-01-09       NaN       NaN       NaN       NaN
2000-01-10       NaN       NaN       NaN       NaN
2000-01-11       NaN       NaN       NaN       NaN
2000-01-12  0.237462 -0.893170 -0.772092 -0.128398

In [35]:
frame.resample("W-THU").ffill()

            Colorado     Texas  New York      Ohio
2000-01-06  0.143061 -1.661158  0.673409  0.259948
2000-01-13  0.237462 -0.893170 -0.772092 -0.128398

In [36]:
frame = pd.DataFrame(np.random.standard_normal((24,4)), index = pd.period_range("1-2000", "12-2001", freq = "M"), columns = ["Colorado", "Texas", "New York", "Ohio"])

In [37]:
frame.head()

         Colorado     Texas  New York      Ohio
2000-01  0.922341 -0.452988 -1.076472  0.206184
2000-02 -0.365971 -0.833715  0.351086  2.738345
2000-03  0.318301  0.892994 -1.390317  0.676781
2000-04 -0.710585  0.055520 -0.338839  0.544784
2000-05  0.274975 -0.938851 -2.086572 -0.547428

In [39]:
annual_frame = frame.resample("Y-DEC").mean()

In [40]:
annual_frame

      Colorado     Texas  New York      Ohio
2000  0.078225 -0.434892 -0.496982  0.321709
2001 -0.050062  0.537327 -0.125253  0.277693

In [41]:
annual_frame.resample("Q-DEC").ffill()

        Colorado     Texas  New York      Ohio
2000Q1  0.078225 -0.434892 -0.496982  0.321709
2000Q2  0.078225 -0.434892 -0.496982  0.321709
2000Q3  0.078225 -0.434892 -0.496982  0.321709
2000Q4  0.078225 -0.434892 -0.496982  0.321709
2001Q1 -0.050062  0.537327 -0.125253  0.277693
2001Q2 -0.050062  0.537327 -0.125253  0.277693
2001Q3 -0.050062  0.537327 -0.125253  0.277693
2001Q4 -0.050062  0.537327 -0.125253  0.277693

In [42]:
annual_frame.resample("Q-DEC", convention="end").asfreq()

        Colorado     Texas  New York      Ohio
2000Q4  0.078225 -0.434892 -0.496982  0.321709
2001Q1       NaN       NaN       NaN       NaN
2001Q2       NaN       NaN       NaN       NaN
2001Q3       NaN       NaN       NaN       NaN
2001Q4 -0.050062  0.537327 -0.125253  0.277693

In [44]:
annual_frame.resample("Q-MAR").ffill()

        Colorado     Texas  New York      Ohio
2000Q4  0.078225 -0.434892 -0.496982  0.321709
2001Q1  0.078225 -0.434892 -0.496982  0.321709
2001Q2  0.078225 -0.434892 -0.496982  0.321709
2001Q3  0.078225 -0.434892 -0.496982  0.321709
2001Q4 -0.050062  0.537327 -0.125253  0.277693
2002Q1 -0.050062  0.537327 -0.125253  0.277693
2002Q2 -0.050062  0.537327 -0.125253  0.277693
2002Q3 -0.050062  0.537327 -0.125253  0.277693

In [45]:
N = 15

In [46]:
times = pd.date_range("2017-05-20 00:00", freq = "1min", periods = N)

In [47]:
df = pd.DataFrame({"time":times, "value":np.arange(N)})

In [48]:
df

                  time  value
0  2017-05-20 00:00:00      0
1  2017-05-20 00:01:00      1
2  2017-05-20 00:02:00      2
3  2017-05-20 00:03:00      3
4  2017-05-20 00:04:00      4
5  2017-05-20 00:05:00      5
6  2017-05-20 00:06:00      6
7  2017-05-20 00:07:00      7
8  2017-05-20 00:08:00      8
9  2017-05-20 00:09:00      9
10 2017-05-20 00:10:00     10
11 2017-05-20 00:11:00     11
12 2017-05-20 00:12:00     12
13 2017-05-20 00:13:00     13
14 2017-05-20 00:14:00     14

In [49]:
df.set_index("time").resample("5min").count()

                     value
time
2017-05-20 00:00:00      5
2017-05-20 00:05:00      5
2017-05-20 00:10:00      5

In [50]:
df2 = pd.DataFrame({"time": times.repeat(3), "key": np.tile(["a", "b", "c"], N), "value": np.arange(N * 3.)})

In [51]:
df2.head(7)

                 time key  value
0 2017-05-20 00:00:00   a    0.0
1 2017-05-20 00:00:00   b    1.0
2 2017-05-20 00:00:00   c    2.0
3 2017-05-20 00:01:00   a    3.0
4 2017-05-20 00:01:00   b    4.0
5 2017-05-20 00:01:00   c    5.0
6 2017-05-20 00:02:00   a    6.0

In [53]:
time_key = pd.Grouper(freq="5min")

In [54]:
resampled = (df2.set_index("time").groupby(["key", time_key]).sum())

In [55]:
resampled

                         value
key time
a   2017-05-20 00:00:00   30.0
    2017-05-20 00:05:00  105.0
    2017-05-20 00:10:00  180.0
b   2017-05-20 00:00:00   35.0
    2017-05-20 00:05:00  110.0
    2017-05-20 00:10:00  185.0
c   2017-05-20 00:00:00   40.0
    2017-05-20 00:05:00  115.0
    2017-05-20 00:10:00  190.0

In [56]:
resampled.reset_index()

  key                time  value
0   a 2017-05-20 00:00:00   30.0
1   a 2017-05-20 00:05:00  105.0
2   a 2017-05-20 00:10:00  180.0
3   b 2017-05-20 00:00:00   35.0
4   b 2017-05-20 00:05:00  110.0
5   b 2017-05-20 00:10:00  185.0
6   c 2017-05-20 00:00:00   40.0
7   c 2017-05-20 00:05:00  115.0
8   c 2017-05-20 00:10:00  190.0