In [14]:
import numpy as np

In [15]:
import pandas as pd

In [16]:
obj2 = pd.Series(np.arange(5.), index = ["a", "b", "c", "d", "e"])

In [17]:
obj2

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [18]:
new_obj = obj2.drop("c")

In [19]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [20]:
obj2.drop(["c", "d"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [21]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index = ["ohio", "colorodo", "utah", "new york"], columns = ["one", "two", "three", "four"])

In [22]:
data

          one  two  three  four
ohio        0    1      2     3
colorodo    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [24]:
data.drop(index = ["colorodo", "ohio"])

          one  two  three  four
utah        8    9     10    11
new york   12   13     14    15

In [26]:
data.drop(columns = ["two"])

          one  three  four
ohio        0      2     3
colorodo    4      6     7
utah        8     10    11
new york   12     14    15

In [27]:
data.drop("two", axis = 1)

          one  three  four
ohio        0      2     3
colorodo    4      6     7
utah        8     10    11
new york   12     14    15

In [28]:
data.drop(["two","four"], axis = "columns")

          one  three
ohio        0      2
colorodo    4      6
utah        8     10
new york   12     14

In [29]:
obj = pd.Series(np.arange(4.), index = ["a", "b", "c", "d"])

In [30]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [31]:
obj["b"]

np.float64(1.0)

In [33]:
obj.iloc[1]

np.float64(1.0)

In [34]:
obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [36]:
obj.iloc[[1,3]]

b    1.0
d    3.0
dtype: float64

In [37]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [38]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [43]:
obj1 = pd.Series([1,2,3], index = [2,0,1])

In [44]:
obj2 = pd.Series([1,2,3], index = ["a","b","c"])

In [45]:
obj1

2    1
0    2
1    3
dtype: int64

In [46]:
obj2

a    1
b    2
c    3
dtype: int64

In [50]:
obj1.iloc[[0,1,2]]

2    1
0    2
1    3
dtype: int64

In [52]:
obj2.iloc[[0,1]]

a    1
b    2
dtype: int64

In [54]:
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [55]:
obj2.loc["b":"c"] = 5

In [56]:
obj2

a    1
b    5
c    5
dtype: int64

In [57]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index = ["ohio", "colorado", "utah", "new york"], columns = ["one", "two", "three", "four"])

In [58]:
data

          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [62]:
data["two"]

ohio         1
colorado     5
utah         9
new york    13
Name: two, dtype: int64

In [63]:
data[["three", "one"]]

          three  one
ohio          2    0
colorado      6    4
utah         10    8
new york     14   12

In [64]:
data[:2]

          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7

In [66]:
data[data["three"]>5]

          one  two  three  four
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [67]:
data < 5

            one    two  three   four
ohio       True   True   True   True
colorado   True  False  False  False
utah      False  False  False  False
new york  False  False  False  False

In [68]:
data[data<5] = 0

In [69]:
data

          one  two  three  four
ohio        0    0      0     0
colorado    0    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [70]:
data

          one  two  three  four
ohio        0    0      0     0
colorado    0    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [71]:
data.loc["colorado"]

one      0
two      5
three    6
four     7
Name: colorado, dtype: int64

In [72]:
data.loc[["colorado", "new york"]]

          one  two  three  four
colorado    0    5      6     7
new york   12   13     14    15

In [73]:
data.loc["colorado", ["two","three"]]

two      5
three    6
Name: colorado, dtype: int64

In [74]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: utah, dtype: int64

In [75]:
data.iloc[[2,1]]

          one  two  three  four
utah        8    9     10    11
colorado    0    5      6     7

In [77]:
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: utah, dtype: int64

In [78]:
data.iloc[[1,2], [3,0,1]]

          four  one  two
colorado     7    0    5
utah        11    8    9

In [80]:
data.loc[:"utah", "two"]

ohio        0
colorado    5
utah        9
Name: two, dtype: int64

In [81]:
data.iloc[:,:3][data.three > 5]

          one  two  three
colorado    0    5      6
utah        8    9     10
new york   12   13     14

In [82]:
data.loc[data.three >= 2]

          one  two  three  four
colorado    0    5      6     7
utah        8    9     10    11
new york   12   13     14    15