In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = pd.DataFrame({
    'x0': [1,2,3,4,5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.]})

In [4]:
data

   x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [5]:
data.columns

Index(['x0', 'x1', 'y'], dtype='str')

In [6]:
data.to_numpy()

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [7]:
df2 = pd.DataFrame(data.to_numpy(), columns = ['one', 'two', 'three'])

In [8]:
df2

   one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [9]:
df3 = data.copy()

In [10]:
df3['strings'] = ['a', 'b', 'c', 'd', 'e']

In [11]:
df3

   x0    x1    y strings
0   1  0.01 -1.5       a
1   2 -0.01  0.0       b
2   3  0.25  3.6       c
3   4 -4.10  1.3       d
4   5  0.00 -2.0       e

In [12]:
df3.to_numpy()

array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.0, 'e']], dtype=object)

In [13]:
model_cols = ['x0', 'x1']

In [14]:
data.loc[:, model_cols].to_numpy()

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [15]:
data['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'], categories = ['a','b'])

In [16]:
data

   x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

In [17]:
dummies = pd.get_dummies(data.category, prefix = 'category')

In [18]:
data_with_dummies = data.drop('category', axis = 1).join(dummies)

In [19]:
data_with_dummies

   x0    x1    y  category_a  category_b
0   1  0.01 -1.5        True       False
1   2 -0.01  0.0       False        True
2   3  0.25  3.6        True       False
3   4 -4.10  1.3        True       False
4   5  0.00 -2.0       False        True