In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
ser = pd.Series(np.arange(3.))

In [5]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [6]:
ser.iloc[-1]

np.float64(2.0)

In [7]:
ser2 = pd.Series(np.arange(3.), index = ["a", "b", "c"])

In [10]:
ser2.iloc[-1]

np.float64(2.0)

In [12]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [15]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index = ["ohio", "colorade", "utah", "new york"], columns = ["one", "two", "three", "four"])

In [16]:
data

          one  two  three  four
ohio        0    1      2     3
colorade    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [17]:
data.loc[:, "one"] = 1

In [18]:
data

          one  two  three  four
ohio        1    1      2     3
colorade    1    5      6     7
utah        1    9     10    11
new york    1   13     14    15

In [19]:
data.iloc[2] = 5

In [20]:
data

          one  two  three  four
ohio        1    1      2     3
colorade    1    5      6     7
utah        5    5      5     5
new york    1   13     14    15

In [21]:
data.loc[data["four"] > 5] = 3

In [22]:
data

          one  two  three  four
ohio        1    1      2     3
colorade    3    3      3     3
utah        5    5      5     5
new york    3    3      3     3

In [23]:
data.loc[data.three == 5, "three"] = 6

In [24]:
data

          one  two  three  four
ohio        1    1      2     3
colorade    3    3      3     3
utah        5    5      6     5
new york    3    3      3     3

In [30]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ["a", "c", "d", "e"])

In [31]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ["a", "c", "e", "f", "g"])

In [32]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [38]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns = list("bcd"), index = ["ohio", "texas", "colorado"])

In [39]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns = list("bde"), index = ["utah", "ohio", "texas", "oregon"])

In [40]:
df1 + df2

            b   c     d   e
colorado  NaN NaN   NaN NaN
ohio      3.0 NaN   6.0 NaN
oregon    NaN NaN   NaN NaN
texas     9.0 NaN  12.0 NaN
utah      NaN NaN   NaN NaN

In [41]:
df1 = pd.DataFrame({"A":[1,2]})

In [42]:
df2 = pd.DataFrame({"B":[3,4]})

In [43]:
df1

   A
0  1
1  2

In [44]:
df2

   B
0  3
1  4

In [45]:
df1 + df2

    A   B
0 NaN NaN
1 NaN NaN