In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns = list("abcd"))

In [4]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns = list("abcde"))

In [5]:
df2.loc[1, "b"] = np.nan

In [6]:
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [7]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [8]:
df1 + df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [9]:
df1.add(df2, fill_value = 0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [10]:
1 / df1

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [11]:
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [12]:
df1.reindex(columns = df2.columns, fill_value = 0)

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [13]:
arr = np.arange(12.).reshape((3,4))

In [14]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [15]:
arr[0]

array([0., 1., 2., 3.])

In [16]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [19]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)), columns = list("bde"), index = ["utah", "ohio", "texas", "orgeon"])

In [20]:
series = frame.iloc[0]

In [21]:
frame

          b     d     e
utah    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
orgeon  9.0  10.0  11.0

In [22]:
series

b    0.0
d    1.0
e    2.0
Name: utah, dtype: float64

In [23]:
frame - series

          b    d    e
utah    0.0  0.0  0.0
ohio    3.0  3.0  3.0
texas   6.0  6.0  6.0
orgeon  9.0  9.0  9.0

In [24]:
series2 = pd.Series(np.arange(3), index = ["b", "e", "f"])

In [25]:
series2

b    0
e    1
f    2
dtype: int64

In [26]:
frame + series2

          b   d     e   f
utah    0.0 NaN   3.0 NaN
ohio    3.0 NaN   6.0 NaN
texas   6.0 NaN   9.0 NaN
orgeon  9.0 NaN  12.0 NaN

In [27]:
series3 = frame["d"]

In [28]:
frame

          b     d     e
utah    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
orgeon  9.0  10.0  11.0

In [29]:
series3

utah       1.0
ohio       4.0
texas      7.0
orgeon    10.0
Name: d, dtype: float64

In [30]:
frame.sub(series3, axis ="index")

          b    d    e
utah   -1.0  0.0  1.0
ohio   -1.0  0.0  1.0
texas  -1.0  0.0  1.0
orgeon -1.0  0.0  1.0