In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
frame = pd.DataFrame(np.random.standard_normal((4,3)), columns = list("bde"), index = ["utah", "ohio", "texas", "oregon"])

In [5]:
frame

               b         d         e
utah    0.476610 -0.348972 -0.287344
ohio    0.986957  1.320442  0.651436
texas  -0.371517 -1.268164 -0.142473
oregon -0.096929  1.213779 -0.637987

In [6]:
np.abs(frame)

               b         d         e
utah    0.476610  0.348972  0.287344
ohio    0.986957  1.320442  0.651436
texas   0.371517  1.268164  0.142473
oregon  0.096929  1.213779  0.637987

In [8]:
def f1(x):
    return x.max() - x.min()

In [9]:
frame.apply(f1)

b    1.358474
d    2.588605
e    1.289423
dtype: float64

In [10]:
frame.apply(f1, axis = "columns")

utah      0.825582
ohio      0.669006
texas     1.125691
oregon    1.851766
dtype: float64

In [11]:
def f2(x):
    return pd.Series([x.min(), x.max()], index = ["min", "max"])

In [12]:
frame.apply(f2)

            b         d         e
min -0.371517 -1.268164 -0.637987
max  0.986957  1.320442  0.651436

In [13]:
def my_format(x):
    return f"{x:.2f}"

In [15]:
frame.map(my_format)

            b      d      e
utah     0.48  -0.35  -0.29
ohio     0.99   1.32   0.65
texas   -0.37  -1.27  -0.14
oregon  -0.10   1.21  -0.64

In [16]:
frame["e"].map(my_format)

utah      -0.29
ohio       0.65
texas     -0.14
oregon    -0.64
Name: e, dtype: str

In [17]:
obj = pd.Series(np.arange(4), index = ["d", "a", "b", "c"])

In [18]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [19]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [20]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)), index = ["three", "one"], columns = ["d", "a", "b", "c"])

In [21]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [22]:
frame.sort_index(axis = "columns")

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [23]:
frame.sort_index(axis = "columns", ascending = False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [24]:
onj = pd.Series([4, 7, -3,2 ])

In [25]:
onj

0    4
1    7
2   -3
3    2
dtype: int64