In [1]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
obj = pd.Series([4,7, -3,2])

In [10]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [11]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [13]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [14]:
obj.sort_values(na_position = "first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [16]:
frame = pd.DataFrame({"b":[4,7,-3,2], "a":[0,1,0,1]})

In [17]:
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [18]:
frame.sort_values("b")

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [19]:
frame.sort_values(["a","b"])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [20]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [21]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [22]:
obj.rank(method = "first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [23]:
obj.rank(ascending = False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [24]:
frame = pd.DataFrame({"b": [4.3,7,-3,2], "a": [0,1,0,1], "c": [-2, 5,8,-2.5]})

In [25]:
frame.rank(axis = "columns")

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0